# Generated by Django 4.1.2 on 2022-12-21 02:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
