# Generated by Django 4.1.2 on 2022-12-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_announcement_body_alter_room_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
