# Generated by Django 4.1.2 on 2022-12-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_council_faculty_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='picture',
            field=models.ImageField(default='achievements.png', null=True, upload_to=''),
        ),
    ]
