# Generated by Django 4.1.2 on 2022-12-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_achievement_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
