# Generated by Django 4.1.2 on 2022-12-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='picture',
        ),
        migrations.AddField(
            model_name='items',
            name='picture1',
            field=models.ImageField(blank=True, default='item.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='items',
            name='picture2',
            field=models.ImageField(blank=True, default='item.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='items',
            name='picture3',
            field=models.ImageField(blank=True, default='item.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.TextField(default='P0.00', max_length=20),
        ),
    ]
