# Generated by Django 4.1.2 on 2022-12-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_items_picture_items_picture1_items_picture2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('role', models.TextField(max_length=200)),
                ('picture', models.ImageField(default='default-dp.jpg', null=True, upload_to='')),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
