# Generated by Django 4.1.2 on 2023-01-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_wall'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='name',
            field=models.CharField(blank=True, default='anonymous', max_length=20),
        ),
        migrations.AlterField(
            model_name='wall',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
