# Generated by Django 4.1.2 on 2023-01-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_wall_name_alter_wall_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wall',
            name='title',
        ),
    ]
